// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"rabc-go/internal/repository"
	"rabc-go/internal/server"
	"rabc-go/internal/task"
	"rabc-go/pkg/app"
	"rabc-go/pkg/log"
	"rabc-go/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db, cleanup, err := repository.NewDB(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	syncedEnforcer, cleanup2, err := repository.NewCasbinEnforcer(viperViper, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(logger, db, syncedEnforcer)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	taskTask := task.NewTask(transaction, logger, sidSid)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userTask := task.NewUserTask(taskTask, userRepository)
	taskServer := server.NewTaskServer(logger, userTask)
	appApp := newApp(logger, taskServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewCasbinEnforcer)

var taskSet = wire.NewSet(task.NewTask, task.NewUserTask)

var serverSet = wire.NewSet(server.NewTaskServer)

// build App
func newApp(logger *log.Logger, task2 *server.TaskServer,
) *app.App {
	return app.NewApp(app.WithServer(task2), app.WithName("demo-task"), app.WithLogger(logger))
}
