// Code generated by MockGen. DO NOT EDIT.
// Source: rabc-go/internal/repository (interfaces: AdminRepository,AdminAuthRepository,AdminUserRepository,PermissionRepository,MenuRepository,RoleRepository,APIRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../test/mocks/repository/admin.go rabc-go/internal/repository AdminRepository,AdminAuthRepository,AdminUserRepository,PermissionRepository,MenuRepository,RoleRepository,APIRepository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	model "rabc-go/internal/model"
	repository "rabc-go/internal/repository"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// AdminUserCreateAtomic mocks base method.
func (m_2 *MockAdminRepository) AdminUserCreateAtomic(ctx context.Context, m *model.AdminUser, roles []string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserCreateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserCreateAtomic indicates an expected call of AdminUserCreateAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserCreateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserCreateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserCreateAtomic), ctx, m, roles)
}

// AdminUserDeleteAtomic mocks base method.
func (m *MockAdminRepository) AdminUserDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserDeleteAtomic indicates an expected call of AdminUserDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserDeleteAtomic), ctx, id)
}

// AdminUserUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) AdminUserUpdateAtomic(ctx context.Context, m *model.AdminUser, roles *[]string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserUpdateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserUpdateAtomic indicates an expected call of AdminUserUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserUpdateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserUpdateAtomic), ctx, m, roles)
}

// APICreate mocks base method.
func (m_2 *MockAdminRepository) APICreate(ctx context.Context, m *model.API) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "APICreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// APICreate indicates an expected call of APICreate.
func (mr *MockAdminRepositoryMockRecorder) APICreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APICreate", reflect.TypeOf((*MockAdminRepository)(nil).APICreate), ctx, m)
}

// APIDeleteAtomic mocks base method.
func (m *MockAdminRepository) APIDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// APIDeleteAtomic indicates an expected call of APIDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) APIDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).APIDeleteAtomic), ctx, id)
}

// APIUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) APIUpdateAtomic(ctx context.Context, m *model.API) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "APIUpdateAtomic", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// APIUpdateAtomic indicates an expected call of APIUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) APIUpdateAtomic(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).APIUpdateAtomic), ctx, m)
}

// GetAdminUser mocks base method.
func (m *MockAdminRepository) GetAdminUser(ctx context.Context, uid uint) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", ctx, uid)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUser), ctx, uid)
}

// GetAdminUserByUsername mocks base method.
func (m *MockAdminRepository) GetAdminUserByUsername(ctx context.Context, username string) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserByUsername", ctx, username)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserByUsername indicates an expected call of GetAdminUserByUsername.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserByUsername", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUserByUsername), ctx, username)
}

// GetAdminUsers mocks base method.
func (m *MockAdminRepository) GetAdminUsers(ctx context.Context, q repository.AdminUserQuery) ([]model.AdminUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUsers", ctx, q)
	ret0, _ := ret[0].([]model.AdminUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAdminUsers indicates an expected call of GetAdminUsers.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUsers(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUsers", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUsers), ctx, q)
}

// GetAPIGroups mocks base method.
func (m *MockAdminRepository) GetAPIGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIGroups indicates an expected call of GetAPIGroups.
func (mr *MockAdminRepositoryMockRecorder) GetAPIGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIGroups", reflect.TypeOf((*MockAdminRepository)(nil).GetAPIGroups), ctx)
}

// GetApis mocks base method.
func (m *MockAdminRepository) GetApis(ctx context.Context, q repository.APIQuery) ([]model.API, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApis", ctx, q)
	ret0, _ := ret[0].([]model.API)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetApis indicates an expected call of GetApis.
func (mr *MockAdminRepositoryMockRecorder) GetApis(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApis", reflect.TypeOf((*MockAdminRepository)(nil).GetApis), ctx, q)
}

// GetMenuList mocks base method.
func (m *MockAdminRepository) GetMenuList(ctx context.Context) ([]model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuList", ctx)
	ret0, _ := ret[0].([]model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuList indicates an expected call of GetMenuList.
func (mr *MockAdminRepositoryMockRecorder) GetMenuList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuList", reflect.TypeOf((*MockAdminRepository)(nil).GetMenuList), ctx)
}

// GetRole mocks base method.
func (m *MockAdminRepository) GetRole(ctx context.Context, id uint) (model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAdminRepositoryMockRecorder) GetRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAdminRepository)(nil).GetRole), ctx, id)
}

// GetRolePermissions mocks base method.
func (m *MockAdminRepository) GetRolePermissions(ctx context.Context, role string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, role)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockAdminRepositoryMockRecorder) GetRolePermissions(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockAdminRepository)(nil).GetRolePermissions), ctx, role)
}

// GetRoles mocks base method.
func (m *MockAdminRepository) GetRoles(ctx context.Context, q repository.RoleQuery) ([]model.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, q)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockAdminRepositoryMockRecorder) GetRoles(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockAdminRepository)(nil).GetRoles), ctx, q)
}

// GetUserPermissions mocks base method.
func (m *MockAdminRepository) GetUserPermissions(ctx context.Context, uid uint) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, uid)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockAdminRepositoryMockRecorder) GetUserPermissions(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockAdminRepository)(nil).GetUserPermissions), ctx, uid)
}

// GetUserRoles mocks base method.
func (m *MockAdminRepository) GetUserRoles(ctx context.Context, uid uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, uid)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAdminRepositoryMockRecorder) GetUserRoles(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAdminRepository)(nil).GetUserRoles), ctx, uid)
}

// MenuCreate mocks base method.
func (m_2 *MockAdminRepository) MenuCreate(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuCreate indicates an expected call of MenuCreate.
func (mr *MockAdminRepositoryMockRecorder) MenuCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuCreate", reflect.TypeOf((*MockAdminRepository)(nil).MenuCreate), ctx, m)
}

// MenuDeleteAtomic mocks base method.
func (m *MockAdminRepository) MenuDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MenuDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuDeleteAtomic indicates an expected call of MenuDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) MenuDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).MenuDeleteAtomic), ctx, id)
}

// MenuUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) MenuUpdateAtomic(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuUpdateAtomic", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuUpdateAtomic indicates an expected call of MenuUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) MenuUpdateAtomic(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).MenuUpdateAtomic), ctx, m)
}

// RoleCreateIfAbsent mocks base method.
func (m_2 *MockAdminRepository) RoleCreateIfAbsent(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleCreateIfAbsent", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleCreateIfAbsent indicates an expected call of RoleCreateIfAbsent.
func (mr *MockAdminRepositoryMockRecorder) RoleCreateIfAbsent(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleCreateIfAbsent", reflect.TypeOf((*MockAdminRepository)(nil).RoleCreateIfAbsent), ctx, m)
}

// RoleDeleteAtomic mocks base method.
func (m *MockAdminRepository) RoleDeleteAtomic(ctx context.Context, id uint, sid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDeleteAtomic", ctx, id, sid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleDeleteAtomic indicates an expected call of RoleDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) RoleDeleteAtomic(ctx, id, sid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).RoleDeleteAtomic), ctx, id, sid)
}

// RoleUpdate mocks base method.
func (m_2 *MockAdminRepository) RoleUpdate(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleUpdate indicates an expected call of RoleUpdate.
func (mr *MockAdminRepositoryMockRecorder) RoleUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleUpdate", reflect.TypeOf((*MockAdminRepository)(nil).RoleUpdate), ctx, m)
}

// UpdateLastLogin mocks base method.
func (m *MockAdminRepository) UpdateLastLogin(ctx context.Context, uid uint, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, uid, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockAdminRepositoryMockRecorder) UpdateLastLogin(ctx, uid, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockAdminRepository)(nil).UpdateLastLogin), ctx, uid, at)
}

// UpdateRolePermission mocks base method.
func (m *MockAdminRepository) UpdateRolePermission(ctx context.Context, role string, permissions map[string]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRolePermission", ctx, role, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRolePermission indicates an expected call of UpdateRolePermission.
func (mr *MockAdminRepositoryMockRecorder) UpdateRolePermission(ctx, role, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRolePermission", reflect.TypeOf((*MockAdminRepository)(nil).UpdateRolePermission), ctx, role, permissions)
}

// MockAdminAuthRepository is a mock of AdminAuthRepository interface.
type MockAdminAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminAuthRepositoryMockRecorder is the mock recorder for MockAdminAuthRepository.
type MockAdminAuthRepositoryMockRecorder struct {
	mock *MockAdminAuthRepository
}

// NewMockAdminAuthRepository creates a new mock instance.
func NewMockAdminAuthRepository(ctrl *gomock.Controller) *MockAdminAuthRepository {
	mock := &MockAdminAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAdminAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminAuthRepository) EXPECT() *MockAdminAuthRepositoryMockRecorder {
	return m.recorder
}

// GetAdminUserByUsername mocks base method.
func (m *MockAdminAuthRepository) GetAdminUserByUsername(ctx context.Context, username string) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserByUsername", ctx, username)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserByUsername indicates an expected call of GetAdminUserByUsername.
func (mr *MockAdminAuthRepositoryMockRecorder) GetAdminUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserByUsername", reflect.TypeOf((*MockAdminAuthRepository)(nil).GetAdminUserByUsername), ctx, username)
}

// UpdateLastLogin mocks base method.
func (m *MockAdminAuthRepository) UpdateLastLogin(ctx context.Context, uid uint, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastLogin", ctx, uid, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastLogin indicates an expected call of UpdateLastLogin.
func (mr *MockAdminAuthRepositoryMockRecorder) UpdateLastLogin(ctx, uid, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastLogin", reflect.TypeOf((*MockAdminAuthRepository)(nil).UpdateLastLogin), ctx, uid, at)
}

// MockAdminUserRepository is a mock of AdminUserRepository interface.
type MockAdminUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserRepositoryMockRecorder is the mock recorder for MockAdminUserRepository.
type MockAdminUserRepositoryMockRecorder struct {
	mock *MockAdminUserRepository
}

// NewMockAdminUserRepository creates a new mock instance.
func NewMockAdminUserRepository(ctrl *gomock.Controller) *MockAdminUserRepository {
	mock := &MockAdminUserRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepository) EXPECT() *MockAdminUserRepositoryMockRecorder {
	return m.recorder
}

// AdminUserCreateAtomic mocks base method.
func (m_2 *MockAdminUserRepository) AdminUserCreateAtomic(ctx context.Context, m *model.AdminUser, roles []string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserCreateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserCreateAtomic indicates an expected call of AdminUserCreateAtomic.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserCreateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserCreateAtomic", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserCreateAtomic), ctx, m, roles)
}

// AdminUserDeleteAtomic mocks base method.
func (m *MockAdminUserRepository) AdminUserDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserDeleteAtomic indicates an expected call of AdminUserDeleteAtomic.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserDeleteAtomic", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserDeleteAtomic), ctx, id)
}

// AdminUserUpdateAtomic mocks base method.
func (m_2 *MockAdminUserRepository) AdminUserUpdateAtomic(ctx context.Context, m *model.AdminUser, roles *[]string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserUpdateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserUpdateAtomic indicates an expected call of AdminUserUpdateAtomic.
func (mr *MockAdminUserRepositoryMockRecorder) AdminUserUpdateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserUpdateAtomic", reflect.TypeOf((*MockAdminUserRepository)(nil).AdminUserUpdateAtomic), ctx, m, roles)
}

// GetAdminUser mocks base method.
func (m *MockAdminUserRepository) GetAdminUser(ctx context.Context, uid uint) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", ctx, uid)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockAdminUserRepositoryMockRecorder) GetAdminUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockAdminUserRepository)(nil).GetAdminUser), ctx, uid)
}

// GetAdminUsers mocks base method.
func (m *MockAdminUserRepository) GetAdminUsers(ctx context.Context, q repository.AdminUserQuery) ([]model.AdminUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUsers", ctx, q)
	ret0, _ := ret[0].([]model.AdminUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAdminUsers indicates an expected call of GetAdminUsers.
func (mr *MockAdminUserRepositoryMockRecorder) GetAdminUsers(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUsers", reflect.TypeOf((*MockAdminUserRepository)(nil).GetAdminUsers), ctx, q)
}

// MockPermissionRepository is a mock of PermissionRepository interface.
type MockPermissionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionRepositoryMockRecorder
	isgomock struct{}
}

// MockPermissionRepositoryMockRecorder is the mock recorder for MockPermissionRepository.
type MockPermissionRepositoryMockRecorder struct {
	mock *MockPermissionRepository
}

// NewMockPermissionRepository creates a new mock instance.
func NewMockPermissionRepository(ctrl *gomock.Controller) *MockPermissionRepository {
	mock := &MockPermissionRepository{ctrl: ctrl}
	mock.recorder = &MockPermissionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionRepository) EXPECT() *MockPermissionRepositoryMockRecorder {
	return m.recorder
}

// GetRolePermissions mocks base method.
func (m *MockPermissionRepository) GetRolePermissions(ctx context.Context, role string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, role)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockPermissionRepositoryMockRecorder) GetRolePermissions(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockPermissionRepository)(nil).GetRolePermissions), ctx, role)
}

// GetUserPermissions mocks base method.
func (m *MockPermissionRepository) GetUserPermissions(ctx context.Context, uid uint) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, uid)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockPermissionRepositoryMockRecorder) GetUserPermissions(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockPermissionRepository)(nil).GetUserPermissions), ctx, uid)
}

// GetUserRoles mocks base method.
func (m *MockPermissionRepository) GetUserRoles(ctx context.Context, uid uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, uid)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockPermissionRepositoryMockRecorder) GetUserRoles(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockPermissionRepository)(nil).GetUserRoles), ctx, uid)
}

// UpdateRolePermission mocks base method.
func (m *MockPermissionRepository) UpdateRolePermission(ctx context.Context, role string, permissions map[string]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRolePermission", ctx, role, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRolePermission indicates an expected call of UpdateRolePermission.
func (mr *MockPermissionRepositoryMockRecorder) UpdateRolePermission(ctx, role, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRolePermission", reflect.TypeOf((*MockPermissionRepository)(nil).UpdateRolePermission), ctx, role, permissions)
}

// MockMenuRepository is a mock of MenuRepository interface.
type MockMenuRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMenuRepositoryMockRecorder
	isgomock struct{}
}

// MockMenuRepositoryMockRecorder is the mock recorder for MockMenuRepository.
type MockMenuRepositoryMockRecorder struct {
	mock *MockMenuRepository
}

// NewMockMenuRepository creates a new mock instance.
func NewMockMenuRepository(ctrl *gomock.Controller) *MockMenuRepository {
	mock := &MockMenuRepository{ctrl: ctrl}
	mock.recorder = &MockMenuRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMenuRepository) EXPECT() *MockMenuRepositoryMockRecorder {
	return m.recorder
}

// GetMenuList mocks base method.
func (m *MockMenuRepository) GetMenuList(ctx context.Context) ([]model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuList", ctx)
	ret0, _ := ret[0].([]model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuList indicates an expected call of GetMenuList.
func (mr *MockMenuRepositoryMockRecorder) GetMenuList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuList", reflect.TypeOf((*MockMenuRepository)(nil).GetMenuList), ctx)
}

// MenuCreate mocks base method.
func (m_2 *MockMenuRepository) MenuCreate(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuCreate indicates an expected call of MenuCreate.
func (mr *MockMenuRepositoryMockRecorder) MenuCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuCreate", reflect.TypeOf((*MockMenuRepository)(nil).MenuCreate), ctx, m)
}

// MenuDeleteAtomic mocks base method.
func (m *MockMenuRepository) MenuDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MenuDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuDeleteAtomic indicates an expected call of MenuDeleteAtomic.
func (mr *MockMenuRepositoryMockRecorder) MenuDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuDeleteAtomic", reflect.TypeOf((*MockMenuRepository)(nil).MenuDeleteAtomic), ctx, id)
}

// MenuUpdateAtomic mocks base method.
func (m_2 *MockMenuRepository) MenuUpdateAtomic(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuUpdateAtomic", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuUpdateAtomic indicates an expected call of MenuUpdateAtomic.
func (mr *MockMenuRepositoryMockRecorder) MenuUpdateAtomic(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuUpdateAtomic", reflect.TypeOf((*MockMenuRepository)(nil).MenuUpdateAtomic), ctx, m)
}

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// GetRole mocks base method.
func (m *MockRoleRepository) GetRole(ctx context.Context, id uint) (model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockRoleRepositoryMockRecorder) GetRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockRoleRepository)(nil).GetRole), ctx, id)
}

// GetRoles mocks base method.
func (m *MockRoleRepository) GetRoles(ctx context.Context, q repository.RoleQuery) ([]model.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, q)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockRoleRepositoryMockRecorder) GetRoles(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockRoleRepository)(nil).GetRoles), ctx, q)
}

// RoleCreateIfAbsent mocks base method.
func (m_2 *MockRoleRepository) RoleCreateIfAbsent(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleCreateIfAbsent", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleCreateIfAbsent indicates an expected call of RoleCreateIfAbsent.
func (mr *MockRoleRepositoryMockRecorder) RoleCreateIfAbsent(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleCreateIfAbsent", reflect.TypeOf((*MockRoleRepository)(nil).RoleCreateIfAbsent), ctx, m)
}

// RoleDeleteAtomic mocks base method.
func (m *MockRoleRepository) RoleDeleteAtomic(ctx context.Context, id uint, sid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDeleteAtomic", ctx, id, sid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleDeleteAtomic indicates an expected call of RoleDeleteAtomic.
func (mr *MockRoleRepositoryMockRecorder) RoleDeleteAtomic(ctx, id, sid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDeleteAtomic", reflect.TypeOf((*MockRoleRepository)(nil).RoleDeleteAtomic), ctx, id, sid)
}

// RoleUpdate mocks base method.
func (m_2 *MockRoleRepository) RoleUpdate(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleUpdate indicates an expected call of RoleUpdate.
func (mr *MockRoleRepositoryMockRecorder) RoleUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleUpdate", reflect.TypeOf((*MockRoleRepository)(nil).RoleUpdate), ctx, m)
}

// MockApiRepository is a mock of APIRepository interface.
type MockApiRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApiRepositoryMockRecorder
	isgomock struct{}
}

// MockApiRepositoryMockRecorder is the mock recorder for MockApiRepository.
type MockApiRepositoryMockRecorder struct {
	mock *MockApiRepository
}

// NewMockApiRepository creates a new mock instance.
func NewMockApiRepository(ctrl *gomock.Controller) *MockApiRepository {
	mock := &MockApiRepository{ctrl: ctrl}
	mock.recorder = &MockApiRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiRepository) EXPECT() *MockApiRepositoryMockRecorder {
	return m.recorder
}

// APICreate mocks base method.
func (m_2 *MockApiRepository) APICreate(ctx context.Context, m *model.API) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "APICreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// APICreate indicates an expected call of APICreate.
func (mr *MockApiRepositoryMockRecorder) APICreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APICreate", reflect.TypeOf((*MockApiRepository)(nil).APICreate), ctx, m)
}

// APIDeleteAtomic mocks base method.
func (m *MockApiRepository) APIDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "APIDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// APIDeleteAtomic indicates an expected call of APIDeleteAtomic.
func (mr *MockApiRepositoryMockRecorder) APIDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIDeleteAtomic", reflect.TypeOf((*MockApiRepository)(nil).APIDeleteAtomic), ctx, id)
}

// APIUpdateAtomic mocks base method.
func (m_2 *MockApiRepository) APIUpdateAtomic(ctx context.Context, m *model.API) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "APIUpdateAtomic", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// APIUpdateAtomic indicates an expected call of APIUpdateAtomic.
func (mr *MockApiRepositoryMockRecorder) APIUpdateAtomic(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "APIUpdateAtomic", reflect.TypeOf((*MockApiRepository)(nil).APIUpdateAtomic), ctx, m)
}

// GetAPIGroups mocks base method.
func (m *MockApiRepository) GetAPIGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIGroups indicates an expected call of GetAPIGroups.
func (mr *MockApiRepositoryMockRecorder) GetAPIGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIGroups", reflect.TypeOf((*MockApiRepository)(nil).GetAPIGroups), ctx)
}

// GetApis mocks base method.
func (m *MockApiRepository) GetApis(ctx context.Context, q repository.APIQuery) ([]model.API, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApis", ctx, q)
	ret0, _ := ret[0].([]model.API)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetApis indicates an expected call of GetApis.
func (mr *MockApiRepositoryMockRecorder) GetApis(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApis", reflect.TypeOf((*MockApiRepository)(nil).GetApis), ctx, q)
}
