// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source=admin.go -destination=../../test/mocks/repository/admin.go
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	v1 "rabc-go/api/v1"
	model "rabc-go/internal/model"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// AdminUserCreate mocks base method.
func (m_2 *MockAdminRepository) AdminUserCreate(ctx context.Context, m *model.AdminUser) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserCreate indicates an expected call of AdminUserCreate.
func (mr *MockAdminRepositoryMockRecorder) AdminUserCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserCreate", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserCreate), ctx, m)
}

// AdminUserCreateAtomic mocks base method.
func (m_2 *MockAdminRepository) AdminUserCreateAtomic(ctx context.Context, m *model.AdminUser, roles []string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserCreateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserCreateAtomic indicates an expected call of AdminUserCreateAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserCreateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserCreateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserCreateAtomic), ctx, m, roles)
}

// AdminUserDelete mocks base method.
func (m *MockAdminRepository) AdminUserDelete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserDelete indicates an expected call of AdminUserDelete.
func (mr *MockAdminRepositoryMockRecorder) AdminUserDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserDelete", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserDelete), ctx, id)
}

// AdminUserDeleteAtomic mocks base method.
func (m *MockAdminRepository) AdminUserDeleteAtomic(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminUserDeleteAtomic", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserDeleteAtomic indicates an expected call of AdminUserDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserDeleteAtomic(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserDeleteAtomic), ctx, id)
}

// AdminUserUpdate mocks base method.
func (m_2 *MockAdminRepository) AdminUserUpdate(ctx context.Context, m *model.AdminUser) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserUpdate indicates an expected call of AdminUserUpdate.
func (mr *MockAdminRepositoryMockRecorder) AdminUserUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserUpdate", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserUpdate), ctx, m)
}

// AdminUserUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) AdminUserUpdateAtomic(ctx context.Context, m *model.AdminUser, roles *[]string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AdminUserUpdateAtomic", ctx, m, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdminUserUpdateAtomic indicates an expected call of AdminUserUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) AdminUserUpdateAtomic(ctx, m, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminUserUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).AdminUserUpdateAtomic), ctx, m, roles)
}

// ApiCreate mocks base method.
func (m_2 *MockAdminRepository) ApiCreate(ctx context.Context, m *model.Api) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ApiCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiCreate indicates an expected call of ApiCreate.
func (mr *MockAdminRepositoryMockRecorder) ApiCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiCreate", reflect.TypeOf((*MockAdminRepository)(nil).ApiCreate), ctx, m)
}

// ApiDelete mocks base method.
func (m *MockAdminRepository) ApiDelete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiDelete indicates an expected call of ApiDelete.
func (mr *MockAdminRepositoryMockRecorder) ApiDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiDelete", reflect.TypeOf((*MockAdminRepository)(nil).ApiDelete), ctx, id)
}

// ApiDeleteAtomic mocks base method.
func (m *MockAdminRepository) ApiDeleteAtomic(ctx context.Context, id uint, oldPath, oldMethod string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApiDeleteAtomic", ctx, id, oldPath, oldMethod)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiDeleteAtomic indicates an expected call of ApiDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) ApiDeleteAtomic(ctx, id, oldPath, oldMethod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).ApiDeleteAtomic), ctx, id, oldPath, oldMethod)
}

// ApiUpdate mocks base method.
func (m_2 *MockAdminRepository) ApiUpdate(ctx context.Context, m *model.Api) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ApiUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiUpdate indicates an expected call of ApiUpdate.
func (mr *MockAdminRepositoryMockRecorder) ApiUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiUpdate", reflect.TypeOf((*MockAdminRepository)(nil).ApiUpdate), ctx, m)
}

// ApiUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) ApiUpdateAtomic(ctx context.Context, m *model.Api, oldPath, oldMethod string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "ApiUpdateAtomic", ctx, m, oldPath, oldMethod)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApiUpdateAtomic indicates an expected call of ApiUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) ApiUpdateAtomic(ctx, m, oldPath, oldMethod any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApiUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).ApiUpdateAtomic), ctx, m, oldPath, oldMethod)
}

// CasbinRoleDelete mocks base method.
func (m *MockAdminRepository) CasbinRoleDelete(ctx context.Context, role string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CasbinRoleDelete", ctx, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// CasbinRoleDelete indicates an expected call of CasbinRoleDelete.
func (mr *MockAdminRepositoryMockRecorder) CasbinRoleDelete(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CasbinRoleDelete", reflect.TypeOf((*MockAdminRepository)(nil).CasbinRoleDelete), ctx, role)
}

// DeleteUserRoles mocks base method.
func (m *MockAdminRepository) DeleteUserRoles(ctx context.Context, uid uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserRoles", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserRoles indicates an expected call of DeleteUserRoles.
func (mr *MockAdminRepositoryMockRecorder) DeleteUserRoles(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserRoles", reflect.TypeOf((*MockAdminRepository)(nil).DeleteUserRoles), ctx, uid)
}

// GetAdminUser mocks base method.
func (m *MockAdminRepository) GetAdminUser(ctx context.Context, uid uint) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUser", ctx, uid)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUser indicates an expected call of GetAdminUser.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUser(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUser", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUser), ctx, uid)
}

// GetAdminUserByUsername mocks base method.
func (m *MockAdminRepository) GetAdminUserByUsername(ctx context.Context, username string) (model.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUserByUsername", ctx, username)
	ret0, _ := ret[0].(model.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminUserByUsername indicates an expected call of GetAdminUserByUsername.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUserByUsername", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUserByUsername), ctx, username)
}

// GetAdminUsers mocks base method.
func (m *MockAdminRepository) GetAdminUsers(ctx context.Context, req *v1.GetAdminUsersRequest) ([]model.AdminUser, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminUsers", ctx, req)
	ret0, _ := ret[0].([]model.AdminUser)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAdminUsers indicates an expected call of GetAdminUsers.
func (mr *MockAdminRepositoryMockRecorder) GetAdminUsers(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminUsers", reflect.TypeOf((*MockAdminRepository)(nil).GetAdminUsers), ctx, req)
}

// GetApi mocks base method.
func (m *MockAdminRepository) GetApi(ctx context.Context, id uint) (model.Api, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApi", ctx, id)
	ret0, _ := ret[0].(model.Api)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApi indicates an expected call of GetApi.
func (mr *MockAdminRepositoryMockRecorder) GetApi(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApi", reflect.TypeOf((*MockAdminRepository)(nil).GetApi), ctx, id)
}

// GetApiGroups mocks base method.
func (m *MockAdminRepository) GetApiGroups(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApiGroups", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApiGroups indicates an expected call of GetApiGroups.
func (mr *MockAdminRepositoryMockRecorder) GetApiGroups(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApiGroups", reflect.TypeOf((*MockAdminRepository)(nil).GetApiGroups), ctx)
}

// GetApis mocks base method.
func (m *MockAdminRepository) GetApis(ctx context.Context, req *v1.GetApisRequest) ([]model.Api, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApis", ctx, req)
	ret0, _ := ret[0].([]model.Api)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetApis indicates an expected call of GetApis.
func (mr *MockAdminRepositoryMockRecorder) GetApis(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApis", reflect.TypeOf((*MockAdminRepository)(nil).GetApis), ctx, req)
}

// GetMenu mocks base method.
func (m *MockAdminRepository) GetMenu(ctx context.Context, id uint) (model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenu", ctx, id)
	ret0, _ := ret[0].(model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenu indicates an expected call of GetMenu.
func (mr *MockAdminRepositoryMockRecorder) GetMenu(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenu", reflect.TypeOf((*MockAdminRepository)(nil).GetMenu), ctx, id)
}

// GetMenuList mocks base method.
func (m *MockAdminRepository) GetMenuList(ctx context.Context) ([]model.Menu, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMenuList", ctx)
	ret0, _ := ret[0].([]model.Menu)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMenuList indicates an expected call of GetMenuList.
func (mr *MockAdminRepositoryMockRecorder) GetMenuList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMenuList", reflect.TypeOf((*MockAdminRepository)(nil).GetMenuList), ctx)
}

// GetRole mocks base method.
func (m *MockAdminRepository) GetRole(ctx context.Context, id uint) (model.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(model.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockAdminRepositoryMockRecorder) GetRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockAdminRepository)(nil).GetRole), ctx, id)
}

// GetRolePermissions mocks base method.
func (m *MockAdminRepository) GetRolePermissions(ctx context.Context, role string) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolePermissions", ctx, role)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolePermissions indicates an expected call of GetRolePermissions.
func (mr *MockAdminRepositoryMockRecorder) GetRolePermissions(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolePermissions", reflect.TypeOf((*MockAdminRepository)(nil).GetRolePermissions), ctx, role)
}

// GetRoles mocks base method.
func (m *MockAdminRepository) GetRoles(ctx context.Context, req *v1.GetRoleListRequest) ([]model.Role, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoles", ctx, req)
	ret0, _ := ret[0].([]model.Role)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoles indicates an expected call of GetRoles.
func (mr *MockAdminRepositoryMockRecorder) GetRoles(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoles", reflect.TypeOf((*MockAdminRepository)(nil).GetRoles), ctx, req)
}

// GetUserPermissions mocks base method.
func (m *MockAdminRepository) GetUserPermissions(ctx context.Context, uid uint) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermissions", ctx, uid)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermissions indicates an expected call of GetUserPermissions.
func (mr *MockAdminRepositoryMockRecorder) GetUserPermissions(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermissions", reflect.TypeOf((*MockAdminRepository)(nil).GetUserPermissions), ctx, uid)
}

// GetUserRoles mocks base method.
func (m *MockAdminRepository) GetUserRoles(ctx context.Context, uid uint) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, uid)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockAdminRepositoryMockRecorder) GetUserRoles(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockAdminRepository)(nil).GetUserRoles), ctx, uid)
}

// MenuCreate mocks base method.
func (m_2 *MockAdminRepository) MenuCreate(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuCreate indicates an expected call of MenuCreate.
func (mr *MockAdminRepositoryMockRecorder) MenuCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuCreate", reflect.TypeOf((*MockAdminRepository)(nil).MenuCreate), ctx, m)
}

// MenuDelete mocks base method.
func (m *MockAdminRepository) MenuDelete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MenuDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuDelete indicates an expected call of MenuDelete.
func (mr *MockAdminRepositoryMockRecorder) MenuDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuDelete", reflect.TypeOf((*MockAdminRepository)(nil).MenuDelete), ctx, id)
}

// MenuDeleteAtomic mocks base method.
func (m *MockAdminRepository) MenuDeleteAtomic(ctx context.Context, id uint, oldPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MenuDeleteAtomic", ctx, id, oldPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuDeleteAtomic indicates an expected call of MenuDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) MenuDeleteAtomic(ctx, id, oldPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).MenuDeleteAtomic), ctx, id, oldPath)
}

// MenuUpdate mocks base method.
func (m_2 *MockAdminRepository) MenuUpdate(ctx context.Context, m *model.Menu) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuUpdate indicates an expected call of MenuUpdate.
func (mr *MockAdminRepositoryMockRecorder) MenuUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuUpdate", reflect.TypeOf((*MockAdminRepository)(nil).MenuUpdate), ctx, m)
}

// MenuUpdateAtomic mocks base method.
func (m_2 *MockAdminRepository) MenuUpdateAtomic(ctx context.Context, m *model.Menu, oldPath string) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "MenuUpdateAtomic", ctx, m, oldPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// MenuUpdateAtomic indicates an expected call of MenuUpdateAtomic.
func (mr *MockAdminRepositoryMockRecorder) MenuUpdateAtomic(ctx, m, oldPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MenuUpdateAtomic", reflect.TypeOf((*MockAdminRepository)(nil).MenuUpdateAtomic), ctx, m, oldPath)
}

// RoleCreate mocks base method.
func (m_2 *MockAdminRepository) RoleCreate(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleCreate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleCreate indicates an expected call of RoleCreate.
func (mr *MockAdminRepositoryMockRecorder) RoleCreate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleCreate", reflect.TypeOf((*MockAdminRepository)(nil).RoleCreate), ctx, m)
}

// RoleCreateIfAbsent mocks base method.
func (m_2 *MockAdminRepository) RoleCreateIfAbsent(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleCreateIfAbsent", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleCreateIfAbsent indicates an expected call of RoleCreateIfAbsent.
func (mr *MockAdminRepositoryMockRecorder) RoleCreateIfAbsent(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleCreateIfAbsent", reflect.TypeOf((*MockAdminRepository)(nil).RoleCreateIfAbsent), ctx, m)
}

// RoleDelete mocks base method.
func (m *MockAdminRepository) RoleDelete(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleDelete indicates an expected call of RoleDelete.
func (mr *MockAdminRepositoryMockRecorder) RoleDelete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDelete", reflect.TypeOf((*MockAdminRepository)(nil).RoleDelete), ctx, id)
}

// RoleDeleteAtomic mocks base method.
func (m *MockAdminRepository) RoleDeleteAtomic(ctx context.Context, id uint, sid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDeleteAtomic", ctx, id, sid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleDeleteAtomic indicates an expected call of RoleDeleteAtomic.
func (mr *MockAdminRepositoryMockRecorder) RoleDeleteAtomic(ctx, id, sid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDeleteAtomic", reflect.TypeOf((*MockAdminRepository)(nil).RoleDeleteAtomic), ctx, id, sid)
}

// RoleUpdate mocks base method.
func (m_2 *MockAdminRepository) RoleUpdate(ctx context.Context, m *model.Role) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RoleUpdate", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RoleUpdate indicates an expected call of RoleUpdate.
func (mr *MockAdminRepositoryMockRecorder) RoleUpdate(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleUpdate", reflect.TypeOf((*MockAdminRepository)(nil).RoleUpdate), ctx, m)
}

// UpdateRolePermission mocks base method.
func (m *MockAdminRepository) UpdateRolePermission(ctx context.Context, role string, permissions map[string]struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRolePermission", ctx, role, permissions)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRolePermission indicates an expected call of UpdateRolePermission.
func (mr *MockAdminRepositoryMockRecorder) UpdateRolePermission(ctx, role, permissions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRolePermission", reflect.TypeOf((*MockAdminRepository)(nil).UpdateRolePermission), ctx, role, permissions)
}

// UpdateUserRoles mocks base method.
func (m *MockAdminRepository) UpdateUserRoles(ctx context.Context, uid uint, roles []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserRoles", ctx, uid, roles)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserRoles indicates an expected call of UpdateUserRoles.
func (mr *MockAdminRepositoryMockRecorder) UpdateUserRoles(ctx, uid, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserRoles", reflect.TypeOf((*MockAdminRepository)(nil).UpdateUserRoles), ctx, uid, roles)
}
