// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"rabc-go/internal/repository"
	"rabc-go/internal/server"
	"rabc-go/pkg/log"
	"rabc-go/pkg/sid"
)

// Injectors from wire.go:

// NewWire 返回一次性种子任务，调用方负责显式驱动 Start/Stop 生命周期。
func NewWire(viperViper *viper.Viper, logger *log.Logger) (*server.SeedServer, func(), error) {
	db, cleanup, err := repository.NewDB(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	sidSid := sid.NewSid()
	syncedEnforcer, cleanup2, err := repository.NewCasbinEnforcer(viperViper, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	seedServer := server.NewSeedServer(db, logger, sidSid, syncedEnforcer, viperViper)
	return seedServer, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewCasbinEnforcer)

var serverSet = wire.NewSet(server.NewSeedServer)
