// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"rabc-go/internal/repository"
	"rabc-go/internal/server"
	"rabc-go/pkg/log"
	"rabc-go/pkg/sid"

	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*server.SeedServer, func(), error) {
	db := repository.NewDB(viperViper, logger)
	sidSid := sid.NewSid()
	syncedEnforcer := repository.NewCasbinEnforcer(viperViper, logger, db)
	seedServer := server.NewSeedServer(db, logger, sidSid, syncedEnforcer, viperViper)
	return seedServer, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewCasbinEnforcer)

var serverSet = wire.NewSet(server.NewSeedServer)
