// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"rabc-go/internal/handler"
	"rabc-go/internal/job"
	"rabc-go/internal/repository"
	"rabc-go/internal/server"
	"rabc-go/internal/service"
	"rabc-go/pkg/app"
	"rabc-go/pkg/jwt"
	"rabc-go/pkg/log"
	"rabc-go/pkg/server/http"
	"rabc-go/pkg/sid"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db, cleanup, err := repository.NewDB(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	syncedEnforcer, cleanup2, err := repository.NewCasbinEnforcer(viperViper, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger, jwtJWT)
	repositoryRepository := repository.NewRepository(logger, db, syncedEnforcer)
	adminRepository := repository.NewAdminRepository(repositoryRepository)
	adminService := service.NewAdminService(serviceService, adminRepository)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, adminHandler, userHandler)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(logger, httpServer, jobServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewCasbinEnforcer, repository.NewAdminRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewAdminService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewAdminHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	logger *log.Logger,
	httpServer *http.Server,
	jobServer *server.JobServer,
) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"), app.WithLogger(logger))
}
