// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"rabc-go/internal/auth"
	"rabc-go/internal/handler"
	"rabc-go/internal/repository"
	"rabc-go/internal/server"
	"rabc-go/internal/service"
	"rabc-go/pkg/app"
	"rabc-go/pkg/jwt"
	"rabc-go/pkg/log"
	"rabc-go/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db, cleanup, err := repository.NewDB(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	syncedEnforcer, cleanup2, err := repository.NewCasbinEnforcer(viperViper, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	handlerHandler := handler.NewHandler(logger)
	serviceService := service.NewService(logger, jwtJWT)
	repositoryRepository := repository.NewRepository(logger, db, syncedEnforcer)
	adminRepository := repository.NewAdminRepository(repositoryRepository)
	client := repository.NewRedis(viperViper)
	authRepository := repository.NewAuthRepository(client)
	authConfig := auth.LoadAuthConfig(viperViper, logger)
	authService := service.NewAuthService(serviceService, authRepository, adminRepository, authConfig)
	adminService := service.NewAdminService(serviceService, adminRepository, authService)
	adminHandler := handler.NewAdminHandler(handlerHandler, adminService, authService)
	authHandler := handler.NewAuthHandler(handlerHandler, authService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, adminHandler, authHandler)
	appApp := newApp(logger, httpServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewCasbinEnforcer, repository.NewAdminRepository, repository.NewRedis, repository.NewAuthRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewAdminService, service.NewAuthService, auth.LoadAuthConfig)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewAdminHandler, handler.NewAuthHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// build App
func newApp(
	logger *log.Logger,
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("demo-server"), app.WithLogger(logger))
}
