// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"rabc-go/internal/admin/rbac/api"
	"rabc-go/internal/admin/rbac/casbinkit"
	"rabc-go/internal/admin/rbac/menu"
	"rabc-go/internal/admin/rbac/permission"
	"rabc-go/internal/admin/rbac/role"
	"rabc-go/internal/admin/rbac/user"
	"rabc-go/internal/auth"
	"rabc-go/internal/platform"
	"rabc-go/internal/server"
	"rabc-go/pkg/app"
	"rabc-go/pkg/jwt"
	"rabc-go/pkg/log"
	"rabc-go/pkg/server/http"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	db, cleanup, err := platform.NewDB(viperViper, logger)
	if err != nil {
		return nil, nil, err
	}
	syncedEnforcer, cleanup2, err := platform.NewCasbinEnforcer(viperViper, logger, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client := platform.NewRedis(viperViper)
	repository := auth.NewRepository(client)
	rbacMu := casbinkit.NewRBACMu()
	repo := user.NewRepo(db, syncedEnforcer, logger, rbacMu)
	config := auth.LoadConfig(viperViper, logger)
	service := auth.NewService(logger, jwtJWT, repository, repo, config)
	handler := auth.NewHandler(service)
	userService := user.NewService(logger, repo, service)
	userHandler := user.NewHandler(userService)
	roleRepo := role.NewRepo(db, syncedEnforcer, logger, rbacMu)
	roleService := role.NewService(roleRepo)
	roleHandler := role.NewHandler(roleService)
	menuRepo := menu.NewRepo(db, syncedEnforcer, logger, rbacMu)
	permissionRepo := permission.NewRepo(db, syncedEnforcer, logger, rbacMu)
	menuService := menu.NewService(logger, menuRepo, permissionRepo)
	menuHandler := menu.NewHandler(menuService)
	apiRepo := api.NewRepo(db, syncedEnforcer, logger, rbacMu)
	apiService := api.NewService(apiRepo)
	apiHandler := api.NewHandler(apiService)
	permissionService := permission.NewService(permissionRepo)
	permissionHandler := permission.NewHandler(permissionService)
	httpServer := server.NewHTTPServer(logger, viperViper, jwtJWT, syncedEnforcer, handler, userHandler, roleHandler, menuHandler, apiHandler, permissionHandler)
	appApp := newApp(logger, httpServer)
	return appApp, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var platformSet = wire.NewSet(platform.NewDB, platform.NewCasbinEnforcer, platform.NewRedis)

var rbacSet = wire.NewSet(casbinkit.NewRBACMu, user.NewRepo, user.NewService, user.NewHandler, role.NewRepo, role.NewService, role.NewHandler, menu.NewRepo, menu.NewService, menu.NewHandler, api.NewRepo, api.NewService, api.NewHandler, permission.NewRepo, permission.NewService, permission.NewHandler, wire.Bind(new(menu.PermissionReader), new(*permission.Repo)), wire.Bind(new(auth.UserLookup), new(*user.Repo)))

var authSet = wire.NewSet(auth.LoadConfig, auth.NewRepository, auth.NewService, auth.NewHandler, wire.Bind(new(user.AuthRevoker), new(*auth.Service)))

var serverSet = wire.NewSet(server.NewHTTPServer)

func newApp(
	logger *log.Logger,
	httpServer *http.Server,
) *app.App {
	return app.NewApp(app.WithServer(httpServer), app.WithName("demo-server"), app.WithLogger(logger))
}
